use aegies_okta;
-- Create DPS_USER table
CREATE TABLE DPS_USER (
    ID VARCHAR(40) NOT NULL,
    LOGIN VARCHAR(100) NOT NULL,
    FIRST_NAME VARCHAR(40),
    LAST_NAME VARCHAR(40),
    EMAIL VARCHAR(100),
    PRIMARY KEY (ID),
    UNIQUE (LOGIN)
);
select * from DPS_USER;
select * from DSS_DPS_EVENT;
Select * from SYNC_META;
SET SQL_SAFE_UPDATES = 1;


DELETE FROM DSS_DPS_EVENT;
SET SQL_SAFE_UPDATES = 0;

-- Create DSS_DPS_EVENT table
CREATE TABLE DSS_DPS_EVENT (
    ID VARCHAR(32) NOT NULL,
    TIMESTAMP DATETIME,
    SESSIONID VARCHAR(32),
    PROFILEID VARCHAR(100)
);



INSERT INTO DPS_USER (ID, LOGIN, FIRST_NAME, LAST_NAME, EMAIL)
VALUES (
    UUID(), -- generates a unique string ID
    'testuser@example.com',
    'Test',
    'User',
    'testuser@example.com'
);

ALTER TABLE DSS_DPS_EVENT
ADD COLUMN NAME VARCHAR(100),
ADD COLUMN EMAIL VARCHAR(100);

ALTER TABLE DSS_DPS_EVENT MODIFY ID VARCHAR(40);
ALTER TABLE DSS_DPS_EVENT MODIFY TIMESTAMP DATETIME;


CREATE TABLE SYNC_META (
    ID INT PRIMARY KEY,
    LAST_SYNC_TIMESTAMP DATETIME NOT NULL
);

INSERT INTO SYNC_META (ID, LAST_SYNC_TIMESTAMP)
VALUES (1, '2024-01-01 00:00:00');

SELECT LAST_SYNC_TIMESTAMP FROM SYNC_META WHERE ID = 1;
